hotfix

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,30 +1,33 @@
 #!/usr/bin/env bash
-#install Nginx and configure it
+#install ngix and have a file that returns the string "Hello World  inside
 
-apt-get update
-
-# Install Nginx
-apt-get install -y nginx
-
-# Stop Nginx service
-service nginx stop
-
-# Update Nginx default configuration
-echo "server {
-    listen 80;
-    root /var/www/html;
+sudo apt-get update -y && \
+sudo apt-get install -y nginx
+if [ $? -eq 0 ]
+then
+    echo -e \
+"http {
+    root /var/www/school;
     index index.html;
-    server_name _;
-
-    location / {
-        return 200 'Hello World!';
+    server {
+        listen 80;
+        location \ {
+        }
     }
 }
-" > /etc/nginx/sites-available/default
-
-# Start Nginx service
-service nginx start
-
-# Test Nginx configuration
-curl -sL -w "%{http_code}\\n" "http://localhost/" -o /dev/null
-
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/school
+    echo "Hello World!" > \
+	/var/www/school/index.html
+    service nginx start
+    if [ $? -ne 0 ]
+    then
+	"Problem starting nginx"
+	exit 1
+    fi
+else
+    echo "Could not install nginx"
+    exit 1
+fi
+exit 0
